### ISSUE TITLE
launch different seeds simulateously 

### ISSUE THREAD

**Issue by ChenyangRan** [vitchyr/rlkit#106]
HI, I want to test different seeds for example/sac.py at the same time.
I use the function named run_experiment_here, but the variant['seed'] should be int.
I use a list such as following:
``` python 
    for seed in seeds:
        run_experiment_here(experiment_function=experiment, variant=variant,
                        exp_id=seed, seed=seed, snapshot_mode='gap', snapshot_gap=10, exp_prefix='HalfCheetahEnv')
```
The error is 
```
Traceback (most recent call last):
  File "/home/ur/RL_code/torch/rlkit/examples/il_sac.py", line 124, in <module>
    exp_id=seed, seed=seed, snapshot_mode='gap', snapshot_gap=10, exp_prefix='HalfCheetahEnv'+str(seed))
  File "/home/ur/RL_code/torch/rlkit/rlkit/launchers/launcher_util.py", line 166, in run_experiment_here
    return experiment_function(variant)
  File "/home/ur/RL_code/torch/rlkit/examples/il_sac.py", line 89, in experiment
    algorithm.train()
  File "/home/ur/RL_code/torch/rlkit/rlkit/core/rl_algorithm.py", line 46, in train
    self._train()
  File "/home/ur/RL_code/torch/rlkit/rlkit/core/il_batch_rl_algorithm.py", line 64, in _train
    gt.stamp('evaluation sampling')
  File "/home/ur/anaconda3/envs/rlkit/lib/python3.5/site-packages/gtimer/public/timer.py", line 151, in stamp
    _stamp(name, elapsed, unique, keep_subdivisions, quick_print)
  File "/home/ur/anaconda3/envs/rlkit/lib/python3.5/site-packages/gtimer/public/timer.py", line 698, in _stamp
    _loop_stamp(name, elapsed, unique)
  File "/home/ur/anaconda3/envs/rlkit/lib/python3.5/site-packages/gtimer/public/timer.py", line 714, in _loop_stamp
    _init_loop_stamp(name, unique)
  File "/home/ur/anaconda3/envs/rlkit/lib/python3.5/site-packages/gtimer/public/timer.py", line 725, in _init_loop_stamp
    raise UniqueNameError("Duplicate stamp name (in or at loop): {}".format(name))
gtimer.local.exceptions.UniqueNameError: Duplicate stamp name (in or at loop): evaluation sampling 
```
Could you please help me? Or is anyother function can launch different function that can do it?
Maybe  run_experiment can do it, but should I use the model 'local' ?
I run it by anaconda.

**Comment by kovacgrgur** [comment]
I believe you can fix this by adding `gt.reset_root() `at the end of the `BatchRLAlgorithm` constructor.
Add it at:` rlkit/core/batch_rl_algorithm.py`  line 43

**Comment by snasiriany** [comment]
I encountered this issue as well, and @kovacgrgur 's solution works! @vitchyr @anair13 would you mind adding this in?

**Comment by vitchyr** [comment]
Feel free to make a PR and I'll merge it in!

**Comment by snasiriany** [comment]
@vitchyr here it is: https://github.com/rail-berkeley/rlkit/pull/142
