### ISSUE TITLE
examples/tsac.py does not run at master

### ISSUE THREAD

**Issue by deq2** [vitchyr/rlkit#13]
Crashes with:

Traceback (most recent call last):
  File "/mounts/target/examples/tsac.py", line 75, in <module>
    experiment(variant)
  File "/mounts/target/examples/tsac.py", line 52, in experiment
    algorithm.to(ptu.device)
  File "/mounts/rlkit-vitchyr/rlkit/torch/torch_rl_algorithm.py", line 30, in to
    net.to(device)
  File "/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 366, in __getattr__
    type(self).__name__, name))
AttributeError: 'TanhGaussianPolicy' object has no attribute 'to'

**Comment by vitchyr** [comment]
This is because your PyTorch is `v0.3`. If you update to PyTorch `v0.4` it should work. If not, feel free to open this ticket again.
