### ISSUE TITLE
ImportError: No module named 'rlkit'

### ISSUE THREAD

**Issue by cww97** [vitchyr/rlkit#16]
Finally I conda install successully.. T_T

```shell
(rlkit) cww97@MAIL-ThinkPad:~/rlkit$ python examples/ddpg.py 
Traceback (most recent call last):
  File "examples/ddpg.py", line 6, in <module>
    from rlkit.envs.wrappers import NormalizedBoxEnv
ImportError: No module named 'rlkit'
```

I know this is a question of python. But it seems that I havenot fix this for years.

how could I import correctly...    T_T

**Comment by cww97** [comment]
Then I copy the file `ddpg.py` here

```
(rlkit) $ cp examples/ddpg.py ddpg.py
(rlkit) $ python ddpg.py 
Traceback (most recent call last):
  File "ddpg.py", line 11, in <module>
    from rlkit.launchers.launcher_util import setup_logger
  File "/home/cww97/rlkit/rlkit/launchers/launcher_util.py", line 16, in <module>
    from rlkit.launchers import config
ImportError: cannot import name 'config'
```

Who am I, Where am I come from, and where should I go....

**Comment by cww97** [comment]
Sorry, I know this must be a stupid question, I just, feel all my hairs lost

**Comment by cww97** [comment]
Oh, thats funny...

I add the path of the project to `.zshrc` (or `.bashrc`)


```
export PYTHONPATH=/home/username/rlkit:$PYTHONPATH
```
example...

`$ source .zshrc`

to test, `$ echo $PYTHONPATH`

then this problem will be allright

I need sleep now
