### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by cww97** [vitchyr/rlkit#56]
I make a little change on oracle.py, like[this](https://github.com/cww97/rlkit/commit/69561369bcf1e6e0226e305f6e0f44d12ae29cbe)

and modify state_based_goal_experiments.py

env -> image_env

the I get

```
Traceback (most recent call last):
  File "pusher_img.py", line 76, in <module>
    use_gpu=True,  # Turn on if you have a GPU
  File "/home/cww97/rlkit/rlkit/launchers/launcher_util.py", line 594, in run_experiment
    **run_experiment_kwargs
  File "/home/cww97/rlkit/rlkit/launchers/launcher_util.py", line 175, in run_experiment_here
    return experiment_function(variant)
  File "/home/cww97/rlkit/rlkit/launchers/img_goal_experiments.py", line 120, in her_td3_experiment
    algorithm.train()
  File "/home/cww97/rlkit/rlkit/core/rl_algorithm.py", line 146, in train
    self.train_online(start_epoch=start_epoch)
  File "/home/cww97/rlkit/rlkit/core/rl_algorithm.py", line 178, in train_online
    self._end_epoch(epoch)
  File "/home/cww97/rlkit/rlkit/core/rl_algorithm.py", line 329, in _end_epoch
    post_epoch_func(self, epoch)
  File "/home/cww97/rlkit/rlkit/launchers/rig_experiments.py", line 525, in save_video
    **dump_video_kwargs)
  File "/home/cww97/rlkit/rlkit/util/video.py", line 87, in dump_video
    skvideo.io.vwrite(filename, outputdata)
  File "/home/cww97/.conda/envs/rlkit/lib/python3.5/site-packages/skvideo/io/io.py", line 64, in vwrite
    writer.writeFrame(videodata[t])
  File "/home/cww97/.conda/envs/rlkit/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 448, in writeFrame
    self._warmStart(M, N, C)
  File "/home/cww97/.conda/envs/rlkit/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 419, in _warmStart
    stdout=self.DEVNULL, stderr=sp.STDOUT)
  File "/home/cww97/.conda/envs/rlkit/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/home/cww97/.conda/envs/rlkit/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

I search a little with google, I know this is a memory problem, then I tried to see if there is any difference.

I compared the oracle and img_pusher

the vidoe outputdata are all 115450416

is this because I miss other coding jobs?

**Comment by cww97** [comment]
I am trying to run RL with only image input(throw all image models)

**Comment by vitchyr** [comment]
You might want to reduce the size of the replay buffer and t he size of the images. It looks like your compute does not have enough memory.
