### ISSUE TITLE
FetchReach her example fails - easy to fix though

### ISSUE THREAD

**Issue by MishaLaskin** [vitchyr/rlkit#64]
the `her_sac_gym_fetch_reach.py` throws the following error when I run it.

```
Traceback (most recent call last):
  File "examples/her/her_sac_gym_fetch_reach.py", line 130, in <module>
    experiment(variant)
  File "examples/her/her_sac_gym_fetch_reach.py", line 90, in experiment
    algorithm.train()
  File "/home/misha/downloads/rlkit/rlkit/core/rl_algorithm.py", line 46, in train
    self._train()
  File "/home/misha/downloads/rlkit/rlkit/core/batch_rl_algorithm.py", line 84, in _train
    self._end_epoch(epoch)
  File "/home/misha/downloads/rlkit/rlkit/core/rl_algorithm.py", line 58, in _end_epoch
    self._log_stats(epoch)
  File "/home/misha/downloads/rlkit/rlkit/core/rl_algorithm.py", line 110, in _log_stats
    eval_util.get_generic_path_information(expl_paths),
  File "/home/misha/downloads/rlkit/rlkit/core/eval_util.py", line 40, in get_generic_path_information
    for p in paths
  File "/home/misha/downloads/rlkit/rlkit/core/eval_util.py", line 40, in <listcomp>
    for p in paths
  File "/home/misha/downloads/rlkit/rlkit/pythonplusplus.py", line 167, in list_of_dicts__to__dict_of_lists
    assert set(d.keys()) == set(keys)
AssertionError
```

This can be fixed by modifying the iterator in  the `list_of_dicts__to__dict_of_lists` function by:

```
if 'TimeLimit.truncated' in d:
            del d['TimeLimit.truncated']
```

However, this is definitely a hack. Probably better to refactor that function in a more principled way.

**Comment by vitchyr** [comment]
Hi Misha, thanks for catching this! I finally got around to it. I unwrapped the time limit wrapper. 90195b2
