### ISSUE TITLE
about cuda error during replay weight

### ISSUE THREAD

**Issue by YunchuZhang** [vitchyr/rlkit#94]
Hi there,
I am trying to train sac with her. After get the expert weight, when I try to visualize the policy, it turns out error that ：
Policy and environment loaded
Traceback (most recent call last):
  File "scripts/run_goal_conditioned_policy.py", line 60, in <module>
    simulate_policy(args)
  File "scripts/run_goal_conditioned_policy.py", line 15, in simulate_policy
    policy = data['trainer/policy']
  File "/home/yunchuz/rlkit/rlkit/samplers/rollout_functions.py", line 41, in multitask_rollout
    a, agent_info = agent.get_action(new_obs, **get_action_kwargs)
  File "/home/yunchuz/rlkit/rlkit/torch/sac/policies.py", line 63, in get_action
    actions = self.get_actions(obs_np[None], deterministic=deterministic)
  File "/home/yunchuz/rlkit/rlkit/torch/sac/policies.py", line 67, in get_actions
    return eval_np(self, obs_np, deterministic=deterministic)[0]
  File "/home/yunchuz/rlkit/rlkit/torch/core.py", line 18, in eval_np
    outputs = module(*torch_args, **torch_kwargs)
  File "/home/yunchuz/miniconda3/envs/rlkit/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yunchuz/rlkit/rlkit/torch/sac/policies.py", line 83, in forward
    h = self.hidden_activation(fc(h))
  File "/home/yunchuz/miniconda3/envs/rlkit/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yunchuz/miniconda3/envs/rlkit/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/yunchuz/miniconda3/envs/rlkit/lib/python3.6/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm

Do you know what is the result for it?

**Comment by rstrudel** [comment]
Hi there,

The error:
`RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat1' in call to _th_addmm`, means that you are trying to multiply tensors located on a gpu with tensors located on a cpu.

If you want to run things on gpu, try adding these lines in the code before doing the rollouts:
`import rlkit.torch.pytorch_util as ptu
ptu.set_gpu_mode(True)`
If on cpu, you simply put the last argument to False

**Comment by YunchuZhang** [comment]
I tried ptu.set_gpu_mode(False). It still has the same error. When I train in GPU and get weights, test on cpu, it has this error. But when I train in cpu get weights  and test in cpu, it will not have this error. Do you know the reason?

**Comment by rstrudel** [comment]
In "scripts/run_goal_conditioned_policy.py", line 15, in simulate_policy
policy = data['trainer/policy']

Add .cpu() at the end of the line and it should set the model weights on your cpu. If you want to evaluate on gpu then you should set the data fed on your gpu first. Pytorch tutorial on tensors is a good ressource to check out how this works.

**Comment by vitchyr** [comment]
Yes, @rstrudel 's suggestiom should work. Otherwise feel free to reopen the issue. Thank you @rstrudel !

**Comment by YunchuZhang** [comment]
thanks, are the data['trainer/policy']  and data['evaluation/policy'] same?

**Comment by vitchyr** [comment]
For SAC, the trainer policy is stochastic while the evaluation one is
deterministic.

**Comment by YunchuZhang** [comment]
thanks, for evaluation deterministic policy, how could i load it to gpu?
    policy.to(ptu.device)
AttributeError: 'MakeDeterministic' object has no attribute 'to'

**Comment by vitchyr** [comment]
Good point. You should be able to do policy.policy.to(...), but l'll put a
fix for that soon.

**Comment by YunchuZhang** [comment]
thanks
